(defun getX (l pos)
  (if (null l)
      (error "getX: list is empty")
      (if (= pos 0)
          (car l)
          (getX (cdr l) (- pos 1))))
)

(defun setX (l pos x)
  (cond ((null l) ())
        ((= pos 0) (cons x (cdr l)))
        (t (cons (car l) (setX (cdr l) (- pos 1) x))))
)

(defun getXY (l x y)
  (getX (getX l y) x)
)

(defun setXY (l x y value)
  (setX l y (setX (getX l y) x value))
)

(defun stringToList (str)
  (stringToListRecursive str 0)
)

(defun stringToListRecursive (str i)
    (if (= (length str) i)
      ()
      (cons (char str i) (stringToListRecursive str (+ i 1)))
    )
)

(defun filter (f lista)
  (if (null lista)
    ()
    (if (funcall f (first lista))
      (cons (first lista) (filter f (cdr lista)))
      (filter f (cdr lista))
    )
  )
)

(defun getListLength (list)
  (if (null list)
    0
  (+ 1 (getListLength (cdr list)))
  )
)

(defun getValueInList (list index)
  (if (= index 0) (car list))
  (getValueInList list (- 1 index))
)

(defun mapa (f lista)
  (if (null lista)
    ()
    (cons (funcall f (first lista)) (mapa f (cdr lista)))
  )
)